// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kazemisoroush/code-refactor-tool/pkg/planner (interfaces: Planner)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/kazemisoroush/code-refactor-tool/pkg/planner/models"
)

// MockPlanner is a mock of Planner interface.
type MockPlanner struct {
	ctrl     *gomock.Controller
	recorder *MockPlannerMockRecorder
}

// MockPlannerMockRecorder is the mock recorder for MockPlanner.
type MockPlannerMockRecorder struct {
	mock *MockPlanner
}

// NewMockPlanner creates a new mock instance.
func NewMockPlanner(ctrl *gomock.Controller) *MockPlanner {
	mock := &MockPlanner{ctrl: ctrl}
	mock.recorder = &MockPlannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanner) EXPECT() *MockPlannerMockRecorder {
	return m.recorder
}

// PlanFixes mocks base method.
func (m *MockPlanner) PlanFixes(arg0 string) (models.FixPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlanFixes", arg0)
	ret0, _ := ret[0].(models.FixPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlanFixes indicates an expected call of PlanFixes.
func (mr *MockPlannerMockRecorder) PlanFixes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlanFixes", reflect.TypeOf((*MockPlanner)(nil).PlanFixes), arg0)
}
