// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kazemisoroush/code-refactor-tool/pkg/fixer (interfaces: Fixer)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/kazemisoroush/code-refactor-tool/pkg/analyzer/models"
)

// MockFixer is a mock of Fixer interface.
type MockFixer struct {
	ctrl     *gomock.Controller
	recorder *MockFixerMockRecorder
}

// MockFixerMockRecorder is the mock recorder for MockFixer.
type MockFixerMockRecorder struct {
	mock *MockFixer
}

// NewMockFixer creates a new mock instance.
func NewMockFixer(ctrl *gomock.Controller) *MockFixer {
	mock := &MockFixer{ctrl: ctrl}
	mock.recorder = &MockFixerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFixer) EXPECT() *MockFixerMockRecorder {
	return m.recorder
}

// Fix mocks base method.
func (m *MockFixer) Fix(arg0 context.Context, arg1 string, arg2 []models.LinterIssue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fix", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fix indicates an expected call of Fix.
func (mr *MockFixerMockRecorder) Fix(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fix", reflect.TypeOf((*MockFixer)(nil).Fix), arg0, arg1, arg2)
}
