// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kazemisoroush/code-refactoring-tool/pkg/ai/builder (interfaces: AgentBuilder)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAgentBuilder is a mock of AgentBuilder interface.
type MockAgentBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockAgentBuilderMockRecorder
}

// MockAgentBuilderMockRecorder is the mock recorder for MockAgentBuilder.
type MockAgentBuilderMockRecorder struct {
	mock *MockAgentBuilder
}

// NewMockAgentBuilder creates a new mock instance.
func NewMockAgentBuilder(ctrl *gomock.Controller) *MockAgentBuilder {
	mock := &MockAgentBuilder{ctrl: ctrl}
	mock.recorder = &MockAgentBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentBuilder) EXPECT() *MockAgentBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockAgentBuilder) Build(arg0 context.Context, arg1 string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Build indicates an expected call of Build.
func (mr *MockAgentBuilderMockRecorder) Build(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockAgentBuilder)(nil).Build), arg0, arg1)
}

// TearDown mocks base method.
func (m *MockAgentBuilder) TearDown(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TearDown", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// TearDown indicates an expected call of TearDown.
func (mr *MockAgentBuilderMockRecorder) TearDown(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TearDown", reflect.TypeOf((*MockAgentBuilder)(nil).TearDown), arg0, arg1, arg2, arg3)
}
