name: Go Refactoring Tool CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'
          cache: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r infra/rds_schema_lambda/requirements_test.txt

      - name: Install Go Dependencies
        run: |
          go mod tidy
          cd infra/stack && go mod tidy

      - name: Install golangci-lint v2
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v2.0.0/golangci-lint-2.0.0-linux-amd64.tar.gz | tar -xz
          sudo mv golangci-lint-2.0.0-linux-amd64/golangci-lint /usr/local/bin/
          golangci-lint version

      - name: Run Linter
        run: |
          golangci-lint -v run
          cd infra/stack && golangci-lint -v run

      - name: Run Tests
        run: |
          go test -v ./...

      - name: Run Infra Tests
        run: |
          cd infra/stack && go test -v ./...

      - name: Run Lambda Tests
        run: |
          cd infra/rds_schema_lambda && pytest .
